fcunited/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from fcutdsite import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('history/', views.history, name = "history"),
    path('yourclub/', include("fcutdsite.urls")),
    path('membership/', views.membership, name = "membership"),
    path('media/', views.media, name = "media"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fcutdsite/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "fcutdsite"
 
urlpatterns = [
    path('', views.yourclub, name = "yourclub"),
    path('fixtures/', views.fixtures, name = "fixtures"),
    path('leaguetable/', views.leaguetable, name = "leaguetable"),
    path('squad/', views.squad, name = "squad"),
    path('stadium/', views.stadium, name = "stadium"),
    path('news/', views.news, name = "news"),
    path('detail/<int:id>',views.detail,name = "detail"),
]

fcutdsite/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.


class News(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Author")
    title = models.CharField(max_length = 50,verbose_name = "Title")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Created Date")
    news_image = models.FileField(blank = True,null = True,verbose_name="Adding Picture")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']

fcutdsite/forms.py
from django import forms
from .models import News
class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ["title","content","news_image"]

fcutdsite/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import NewsForm
from .models import News
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    news = News.objects.order_by('-created_date')[0:3]
    context = {
        "news":news
    }
    return render(request,"index.html",context)

def history(request):
    return render(request,"history.html")

def membership(request):
    return render(request,"membership.html")

def media(request):
    return render(request,"media.html")
 
def fixtures(request):
    return render(request,"fixtures.html")

def leaguetable(request):
    return render(request,"leaguetable.html")

def yourclub(request):
    return render(request,"yourclub.html")

def squad(request):
    return render(request,"squad.html")

def stadium(request):
    return render(request,"stadium.html")

def news(request):
    news = News.objects.all()
    context = {
        "news":news
    }
    return render(request,"news.html",context)

def detail(request,id):
    news = get_object_or_404(News,id = id)

    #comments = article.comments.all()
    return render(request,"detail.html",{"news":news})

templates/detail.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
<center>
<header class="jumbotron" style="background-color: rgb(233, 228, 220);">

<img src="{% static 'images/5.png' %}" alt=""><br><br><hr>

<div class="row">
  <center>
  <!-- Post Content Column -->
  <div class="col-lg-8">
    <center>
    <!-- Title -->
    <h3 class="mt-4">{{news.title}}</h3>
    <hr>

    

    <!-- Preview Image 

    {% if news.news_image %}
    <img class="img-fluid rounded" src="{{news.news_image.url}}" alt="" height="400" width="400">
    {% endif %}
   

    <hr> -->

    <!-- Post Content -->
    <div class="card" style="background-color: rgba(204, 204, 204, 0.507);">
      <div class="card-body">
        {{news.content|safe}}
      </div>
    </div>

    <!-- <p class="lead" style="text-align: center;">
        {{news.content|safe}}
    </p> -->
 
    <hr>
    <!-- Date/Time -->
    <p><small>Haber Tarihi : {{news.created_date}}</small></p>

    <hr>
  </center>
  </div>
</center>
</div>

</header>
</center>
{% endblock body %}

templates/history.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
<center>
<header class="jumbotron my-4" style="background-color: rgb(233, 228, 220);">
<img src="{% static 'images/forthebanks.png' %}" alt=""><br><br><hr>
<h3>Tarihimiz</h3><hr>
<h5>Kuruluş</h5><hr>
<p>"Malcolm Glazer'ın Manchester United'ı satın almasını protesto eden kulüp" 'FC United'ı tanımlamak için sıklıkla kullanılan bir açıklamadır. "Amerikan işgali" olmadan FC United'ın kurulamayacağından şüphe olmasa da, tek sebep bu değildi.
</p>
<p>Bir Manchester kurumunun, Manchester halkından zorla alınması (çalınması); televizyon kanalları yararına başlama saatlerini değiştiren, 'yeni' taraftarlarıyla tam-koltuklu stadyumlarda ruhsuz şekilde oturup maç izleten ve uçuk bilet fiyatlarıyla halkı futboldan uzaklaştıran iğrenç bir piramidin tepesiydi.
</p>
<p>Mayıs 2005'e kadar bazı taraftarlarımız için zaten bıçak kemiğe dayanmıştı. Glazer'ın işgalinin Rupert Murdoch'unki gibi engellenememesi "son çare" fikrini tekrar diriltti ve FC United'ın tohumları atıldı. Endüstriyelleşmiş ve köhneleşmiş futbola karşı savaşmaya devam etmek isteyen cesur bir grup kurucu "Yönetim Kurulu"nu oluşturdu ve FC United of Manchester'ı kurdu.
</p>
<p>Uzun tartışmaların sonunda başka bir kulübü desteklemek ya da başka bir kulüple birleşmek yerine, tamamen taraftarlarına ait olan demokratik usullerle karar alan bir futbol kulübünün kurulmasına karar verildi. Bugün kulübümüz FC United; "BİZİM KULÜBÜMÜZ,BİZİM KURALLARIMIZ" mentalitesiyle ve dünyanın dört bir köşesinden binlerce taraftarının desteğiyle futbol dünyasındaki anlamlı mücadelesine devam ediyor.
</p>      
<hr>
</header>
</center>
{% endblock body %}

templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'images/fcum300.png' %}" alt="">    FC United Of Manchester Türkiye</a>
      <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span> 
      </button>-->
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'fcutdsite:yourclub' %}">Senin Kulübün</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'history' %}">Tarihimiz</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'membership' %}">Üyelik/Eş-Sahiplik</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="http://www.fcumshop.co.uk/showpage.php?page=page1" target="_blank">Mağaza</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'media' %}">İletişim</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/includes/your_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'images/fcum300.png' %}" alt="">    FC United Of Manchester Türkiye</a>
      <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span> 
      </button>-->
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'fcutdsite:yourclub' %}">Senin Kulübün</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'history' %}">Tarihimiz</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'membership' %}">Üyelik/Eş-Sahiplik</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="http://www.fcumshop.co.uk/showpage.php?page=page1" target="_blank">Mağaza</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'media' %}">İletişim</a>
          </li>
        </ul>
      </div>
    </div>
</nav>
<hr>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    
    <div class="container">
      <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span> 
      </button>-->
      <div class="collapse navbar-collapse justify-content-md-center" id="navbarResponsive">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'fcutdsite:squad' %}">Takım Kadrosu</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'fcutdsite:fixtures' %}">Fikstür</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'fcutdsite:leaguetable' %}">Puan Durumu</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'fcutdsite:stadium' %}">Evimiz : Broadhurst Park</a>
          </li>
        </ul>
      </div>
    </div>

</nav>

templates/index.html
{% extends "layout.html" %}
{% load static %}
{% block body %}
<!-- Page Content -->
<div class="container">

    <!-- Jumbotron Header -->
    <header class="jumbotron my-4">
      <center>
      <h2>FC United Of Manchester Türkçe Resmi Web Sitesine Hoşgeldiniz!</h2><br>
	  <img src="{% static 'images/6.png' %}" alt=""><br><br>
      <h5>Taraftarlarının "kulüp müşterisi" değil "kulüp eş-sahibi/hissedarı" olduğu, kulüplerinin kararlarına katılabildiği, kâr yapmayı değil kaliteli futbol kültürü oluşturmayı amaçlayan İngiltere Alt-Lig kulübü:</h5><br>
      <h2>FC UNITED OF MANCHESTER</h2>
      <hr>
      <div class="w3-container w3-padding w3-fcred w3-left-align w3-large whitetitle"><b>Kulübümüzün Sesi : FCUM Radio</b><br>
      </div><br>
      <script src="https://embed.radio.co/player/cd42370.js"></script><hr>
    

    
  <h2 class="my-4">Kulübümüzden Haberler :</h2>
  <center>
  <table class="table" style="background-color: rgba(255, 253, 249, 0.671); max-width: 65%;">
    <tbody>
      {% for n in news %}
      <tr>

        <td>
          {% if n.news_image %}
          <a href="{% url 'fcutdsite:detail' n.id %}"><img class="img-fluid rounded" src="{{n.news_image.url}}" alt="" height="50" width="50"></a>
          {% endif %}
          </td>
        <td style="vertical-align: middle;"><a href="{% url 'fcutdsite:detail' n.id %}">{{n.title}}</a></td>
        <!-- <td>{{n.created_date}}</td> -->
      </tr>
      {% endfor %}
    </tbody>
  </table>
</center>
 



      <!-- Page Heading 
  <div class="row">
    
    <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
      {% for n in news %}
      <div class="card h-100">
        
        {% if n.news_image %}
        <img class="img-fluid rounded" src="{{n.news_image.url}}" alt="" height="250" width="250">
        {% endif %}
        <div class="card-body">
          <h4 class="card-title">
            <a href="{% url 'fcutdsite:detail' n.id %}">{{n.title}}</a>
          </h4>
          <p class="card-text">
            {{n.content|safe|truncatewords:50}}
          </p>
        </div>
      </div>
      {% endfor %}
    </div>

  </div> -->

  <!-- Pagination -->
  <ul class="pagination justify-content-center">
    <li class="page-item" style="text-align: center;">
      <a class="page-link" href="{% url 'fcutdsite:news' %}">Tüm Haberler</a>
    </li>
  </ul> 
  <hr>
  


</center>
</header>
</div>
<!-- /.container -->




{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/heroic-features.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    <title>FC United Of Manchester Türkiye</title>
</head>
<body style = "background-color : rgb(146, 146, 146);">  
        {% include "includes/navbar.html" %}

        <div style = "margin-top : 60px; margin-bottom:25px;" class = "container">
            {% block body %}
            
            {% endblock body %}
        </div>
        <!-- Footer -->
        <footer class="py-5 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; 2005-2020 FC United of Manchester (except fixtures, tables and images used by kind permission of their respective rights holders).</p>
	            <p class="m-0 text-center text-white">All rights reserved.</p>
            </div>
        <!-- /.container -->
        </footer>
    

        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  
    </body>
</html>

templates/media.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
<center>
<header class="jumbotron my-4" style="background-color: rgb(233, 228, 220);">
<img src="{% static 'images/formedia.png' %}" alt=""><br><br>
<h3>İletişim</h3>
<hr>
<table class="table" style="background-color: rgba(255, 253, 249, 0.671); max-width: 35%;">
    <tbody>
        <tr>
        <td>
            <a href="https://twitter.com/FcUnited_Turk" target="_blank"><img class="img-fluid rounded" src="{% static 'images/twitter.png' %}" alt="" height="50" width="50">
            </a>
        </td>
        <td style="vertical-align: middle;">
            <a href="https://twitter.com/FcUnited_Turk" target="_blank">FC United of Manchester Twitter (Türkçe)
            </a>
        </td>
        </tr>
        <tr>
        <td>
            <a href="https://twitter.com/FCUnitedMcr" target="_blank"><img class="img-fluid rounded" src="{% static 'images/twitter.png' %}" alt="" height="50" width="50">
            </a>
        </td>
        <td style="vertical-align: middle;">
            <a href="https://twitter.com/FCUnitedMcr" target="_blank">FC United of Manchester Twitter (English)
            </a>
        </td>
        </tr>
        <tr>
        <td>
            <a href="http://www.fc-utd.co.uk/index.php" target="_blank"><img class="img-fluid rounded" src="{% static 'images/fcunited.png' %}" alt="" height="50" width="50">
            </a>
        </td>
        <td style="vertical-align: middle;">
            <a href="http://www.fc-utd.co.uk/index.php" target="_blank">FC United of Manchester Website (English)
            </a>
        </td>
        </tr>
        <tr>
        <td>
            <a href="https://vimeo.com/channels/fcumtv" target="_blank"><img class="img-fluid rounded" src="{% static 'images/fcumtv.jfif' %}" alt="" height="50" width="50">
            </a>
        </td>
        <td style="vertical-align: middle;">
            <a href="https://vimeo.com/channels/fcumtv" target="_blank">FCUM TV
            </a>
        </td>
        </tr>
        <tr>
        <td>
            <a href="http://fc-radio.co.uk/" target="_blank"><img class="img-fluid rounded" src="{% static 'images/fcumradio.png' %}" alt="" height="50" width="50">
            </a>
        </td>
        <td style="vertical-align: middle;">
            <a href="http://fc-radio.co.uk/" target="_blank">FCUM RADIO
            </a>
        </td>
        </tr>
        <tr>
        <td>
            <a href="https://www.youtube.com/user/FCUnitedMcr" target="_blank"><img class="img-fluid rounded" src="{% static 'images/youtube.png' %}" alt="" height="50" width="50">
            </a>
        </td>
        <td style="vertical-align: middle;">
            <a href="https://www.youtube.com/user/FCUnitedMcr" target="_blank">FC United of Manchester - Youtube
            </a>
        </td>
        </tr>
        <tr>
        <td>
            <a href="https://www.instagram.com/fcutdofmanc/" target="_blank"><img class="img-fluid rounded" src="{% static 'images/instagram.png' %}" alt="" height="50" width="50">
            </a>
        </td>
        <td style="vertical-align: middle;">
            <a href="https://www.instagram.com/fcutdofmanc/" target="_blank">FC United of Manchester - Instagram
            </a>
        </td>
        </tr>
        <tr>
        <td>
            <a href="https://www.facebook.com/FCUnitedMcr" target="_blank"><img class="img-fluid rounded" src="{% static 'images/facebook.jpg' %}" alt="" height="50" width="50">
            </a>
        </td>
        <td style="vertical-align: middle;">
            <a href="https://www.facebook.com/FCUnitedMcr" target="_blank">FC United of Manchester - Facebook
            </a>
        </td>
        </tr>

        <tr>
        <td>
            <img class="img-fluid rounded" src="{% static 'images/Gmail.ico' %}" alt="" height="50" width="50">
        </td>
        <td style="vertical-align: middle;">
            fcunitedturk@gmail.com 
        </td>
        </tr>
        <tr>
        <td>
            <img class="img-fluid rounded" src="{% static 'images/fcunited.png' %}" alt="" height="50" width="50">
        </td>
        <td style="vertical-align: middle;">
            office@fc-utd.co.uk 
        </td>
        </tr>
    </tbody>
</table>
<hr>

</header>
</center>
{% endblock body %}

templates/membership.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
<center>
<header class="jumbotron my-4" style="background-color: rgb(233, 228, 220);">
<img src="{% static 'images/media.png' %}" alt=""><br><br>
<h3>Üyelerimiz/Kulüp Sahipleri</h3>
<hr>
<img src="{% static 'images/Co-owners.png' %}" alt="">
<hr>
<p>FC United'a şuan <b>1847</b> üyesi eş-hissedarlık usulüyle sahip. Ayrıca <b>250</b> çok değerli çocuk üyemiz var!
</p>
<p>Kulübümüzün yönetim kurulu seçimi vb. tüm büyük kararları her bir üyesinin eşit ve demokratik bir şekilde vereceği oylarla alınmaktadır.
</p>
<p>Sen de dünyanın neresinde olursan ol (yıllık sadece 15£ karşılığında) kulübümüzün sahiplerinden/üyelerinden biri olabilirsin! Detaylı bilgi için lütfen <a href="http://www.fc-utd.co.uk/members.php">bu adresi</a> ziyaret edin.
</p>
<hr>
<img src="{% static 'images/Co-owners2.png' %}" alt="">
<hr>
<h3>Kombine Bilet Sahipleri</h3>
<hr>
<img src="{% static 'images/kombine.png' %}" alt="">
<hr>
<p>Bu sezon <b>860</b> yetişkin ve <b>158</b> 18 yaş altı genç/çocuk olmak üzere toplam <b>1018</b> kombine bilet sahibi taraftarımız bulunmaktadır.
</p>
<p>Kombine bilet sahibi olmak için lütfen <a href="http://www.fc-utd.co.uk/story.php?story_id=8328">bu adresi</a> ziyaret edin.
</p>
<hr>
<img src="{% static 'images/kombine-2.png' %}" alt="">
<hr>
</header>
</center>
{% endblock body %}

templates/news.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
<center>
<header class="jumbotron my-4" style="background-color: rgb(233, 228, 220);">
<img src="{% static 'images/5.png' %}" alt=""><br><br>
<h3>Kulübümüzden Haberler</h3>

<table class="table" style="background-color: rgba(255, 253, 249, 0.671); max-width: 90%;">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">Başlık</th>
            <th scope="col">Tarih</th>
          </tr>
        </thead>
        <tbody>
          {% for n in news %}
          <tr>
            <td style="vertical-align: middle;"><a href="{% url 'fcutdsite:detail' n.id %}"><img class="img-fluid rounded" src="{{n.news_image.url}}" alt="" height="50" width="50"></a></td>
            <td style="vertical-align: middle;"><a href="{% url 'fcutdsite:detail' n.id %}">{{n.title}}</a></td>
            <td style="vertical-align: middle;">{{n.created_date}}</td>
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
        
        
</header>
</center>
{% endblock body %}

<!-- </a> -->

templates/stadium.html
{% extends "yourclub_layout.html" %}
{% load static %}

{% block body %}
<header class="jumbotron my-4" style="background-color: rgb(233, 228, 220);">
<center>
<img src="{% static 'images/broadhurstpark1.png' %}" alt=""><br><br>
<h1>EVİMİZ : BROADHURST PARK</h1>
<h3>Adres: 310 Lightbowne Rd, Moston, Manchester, M40 0FJ</h3>
<h3>Kapasite: 4,400</h3>
<hr>
<h4>Evimizi Tanıyalım</h4>
<p>Broadhurst Park, İngiltere’nin en yeni ve taraftarlara ait bir futbol kulübü tarafından inşa ve finanse edilen ilk stadyumu.
</p>
<p>Evimiz; futbol taraftarlarının bir vizyon ortaya koyarak birlikte neleri başarabileceğinin en güzel ve en güncel örneklerinden biri. FC United üyeleri Broadhurst Park'ın tasarım ve yapım sürecinde her aşamada yer aldı ve sonuçta bu güzel futbol mabed ortaya çıktı.
</p>
<p>FC Business Magazine tarafından ülkenin yeni inşa edilmiş en iyi alt-lig stadyumu olarak nitelendirilen Broadhurst Park, aynı zamanda eşsiz bir yeşil alan. FC United, £ 4,000 Grow Wild topluluk projesi ödülünü kazandıktan sonra İngiltere'de ilk polen-dostu futbol stadyumunu yaratmaya çalışıyor.
</p>
<p>Bir "topluluk" (community) tesisi olarak, Broadhurst Park her gün yerel halk tarafından kullanılıyor ve çeşitli spor ve eğlence aktivitelerine ev sahipliği yapıyor. Yerel topluluk (Manchester Community), işletmeler ve diğer kuruluşların kiralayabileceği iyi donanımlı bir çok-amaçlı-odası ve toplantı alanları da mevcut.
</p>
<p>6,3 milyon £ değerindeki tesisin finansmanı çeşitli kaynaklardan geldi. FC United taraftarları, öncü bir "Topluluk Paylaşım Programı"ndan 2 milyon sterlin topladı ve diğer fon toplama işlemlerinden 1 milyon sterline yakın gelir elde edildi. Ayrıca Sport England (Iconic Facilities Fund), the Football Foundation (FSIF), Football Foundation (Community Facilities Fund), Manchester City Council, Social Investment Business (My Community Rights), Manchester College and Viridor'dan da hibe şeklinde yardım sağlanmıştır.
</p>
<hr>
<img src="{% static 'images/stadium2.png' %}" alt="">
<hr>






</center>
</header>
{% endblock body %}

templates/yourclub.html
{% extends "yourclub_layout.html" %}
{% load static %}

{% block body %}

<header class="jumbotron my-4" style="background-color: rgb(233, 228, 220);">

<center>

<h3>Kulübümüz FC United of Manchester</h3>
<h5>Kulübümüzün kadrosuna, fikstürüne, puan durumuna ve evimiz Broadhurst Park hakkında ayrıntılı bilgiye bu sayfadan ulaşabilirsiniz!</h5>
<hr>
<a href="{% url 'fcutdsite:yourclub' %}"><img src="{% static 'images/fcumtext.png' %}" alt=""></a>
<hr>

</center>

</header>

{% endblock body %}

templates/yourclub_layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/heroic-features.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    <title>FC United Of Manchester Türkiye</title>
</head>
<body style = "background-color : rgb(146, 146, 146);">  
        
        {% include "includes/your_navbar.html" %}

        <div style = "margin-top : 5px; margin-bottom:25px;" class = "container">
            {% block body %}
            
            {% endblock body %}
        </div>
        <!-- Footer -->
        <footer class="py-5 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; 2005-2020 FC United of Manchester (except fixtures, tables and images used by kind permission of their respective rights holders).</p>
	            <p class="m-0 text-center text-white">All rights reserved.</p>
            </div>
        <!-- /.container -->
        </footer>
    

        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  
    </body>
</html>